---


- name: Install Supervisor
  apt: name={{ item }} state=installed
  with_items:
    - supervisor

- name: Create the Gunicorn config directory
  file: path=/etc/gunicorn state=directory owner={{ user_name }} group={{ user_name }} mode=0777

- name: Create the Gunicorn config file in /etc/gunicorn/
  template: src=gunicorn.conf.j2 dest=/etc/gunicorn/gunicorn.conf

- name: Create the Gunicorn log directory
  file: path=/var/log/gunicorn state=directory owner={{ user_name }} group={{ user_name }} mode=0777

- name: Create the Supervisor config file for Gunicorn
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/gunicorn.conf

- name: Re-read the Supervisor config files
  supervisorctl: name=gunicorn state=present

- name: Start Gunicorn with supervisord
  supervisorctl: name=gunicorn state=restarted
  when: enabled

- name: Stop Gunicorn for local dev
  supervisorctl: name=gunicorn state=stopped
  when: not enabled
