---

- name: Install nginx
  apt: name={{ item }} state=installed
  with_items:
    - nginx

- name: Create the Nginx configuration file for SSL
  template: src=site_ssl.conf.j2 dest=/etc/nginx/sites-available/{{ project_name }}
  when: use_ssl

- name: Create the Nginx configuration file (non-SSL)
  template: src=site.conf.j2 dest=/etc/nginx/sites-available/{{ project_name }}
  when: not use_ssl

- name: Ensure that the default site is removed
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ project_name }} dest=/etc/nginx/sites-enabled/{{ project_name }} state=link
  notify: reload nginx

- name: Ensure Nginx service is started, enable service on restart
  service: name=nginx state=restarted enabled=yes
  when: enabled

# needs to notify handler to come after the restart handlers
- name: Stop nginx for local dev, disable service
  service: name=nginx state=stopped enabled=no
  notify: stop nginx
  when: not enabled
